import type { Metadata } from "next";
import { Lora, Fira_Sans } from "next/font/google";
import "./globals.css";

export const titleText = Lora({
  subsets: ["latin"],
  display: "swap",
  style: ["normal", "italic"],
  variable: "--font-title",
  weight: ["400", "500", "600", "700"],
});

export const bodyText = Fira_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-body",
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bodyText.variable} ${titleText.variable}`}>
        {children}
      </body>
    </html>
  );
}
